name: 🪲 Bug Report
description: Report an issue that should be fixed
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report! It helps make markdown-peek better for everyone.

        Make sure you are running the latest version of markdown-peek. The bug you are experiencing may already have been fixed.

        Please try to include as much information as possible.

  - type: input
    id: version
    attributes:
      label: What version is running?
      description: Copy the output of `mdpeek --version`
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: What platform is your computer?
      description: |
        For MacOS and Linux: copy the output of `uname -mprs`
        Unfortunately Windows Powershell is not supported, only WSL is available.
  - type: textarea
    id: content
    attributes:
      label: What content did you try to preview?
      description: |
        Copy your content here.
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: What steps can reproduce the bug?
      description: Explain the bug and provide that can reproduce it.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is the expected behavior?
      description: If possible, please provide text instead of a screenshot.
  - type: textarea
    id: notes
    attributes:
      label: Additional information
      description: Is there anything else you think we should know?
